# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Godlp < Formula
  desc ""
  homepage "https://github.com/mcreekmore/godlp"
  version "0.1.0"

  on_macos do
    url "https://github.com/mcreekmore/godlp/releases/download/v0.1.0/godlp_0.1.0_darwin_all.tar.gz"
    sha256 "a44ed51c3c6b7472d49fc345971e06f404abc68397aeb069b475cce3e9b9bc60"

    def install
      bin.install "godlp"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mcreekmore/godlp/releases/download/v0.1.0/godlp_0.1.0_linux_amd64.tar.gz"
      sha256 "1b851a22573ef56412f1357da3678bfcbf573e587255e2d6f1e2c003e2c095d7"

      def install
        bin.install "godlp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mcreekmore/godlp/releases/download/v0.1.0/godlp_0.1.0_linux_arm64.tar.gz"
      sha256 "406d06f8ccc9f4fd40038de79afd81594292787cc7fc60273c1dc7b87ea77534"

      def install
        bin.install "godlp"
      end
    end
  end
end
