# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mcreekmore < Formula
  desc ""
  homepage "https://github.com/mcreekmore/godlp"
  version "0.1.1"

  on_macos do
    url "https://github.com/mcreekmore/godlp/releases/download/v0.1.1/godlp_0.1.1_darwin_all.tar.gz"
    sha256 "0d67a0afbc09c034290af6248a7f7648a2b81df653a78dd5d8867442100a02ab"

    def install
      bin.install "godlp"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mcreekmore/godlp/releases/download/v0.1.1/godlp_0.1.1_linux_amd64.tar.gz"
      sha256 "cfa81fd83b389636b0efd770e141f8c6fd76d5c9469388f040e6583c8430c19b"

      def install
        bin.install "godlp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mcreekmore/godlp/releases/download/v0.1.1/godlp_0.1.1_linux_arm64.tar.gz"
      sha256 "175fbab2709beff242b5ea5b4589dfb9d8516b6705dc28e5cc35397d3a4b7262"

      def install
        bin.install "godlp"
      end
    end
  end
end
