# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Godlp < Formula
  desc "A convenient wrapper for yt-dlp"
  homepage "https://github.com/mcreekmore/godlp"
  version "0.1.1"

  on_macos do
    url "https://github.com/mcreekmore/godlp/releases/download/v0.1.1/godlp_0.1.1_darwin_all.tar.gz"
    sha256 "1a06c19984f0fe9f51677786380bf944d78234404e612af0c09c2b21b7d5f4f3"

    def install
      bin.install "godlp"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mcreekmore/godlp/releases/download/v0.1.1/godlp_0.1.1_linux_arm64.tar.gz"
      sha256 "7a137612902ec3fdfcaf0f48362d324be87311fb993e551cb2aba844b82465f7"

      def install
        bin.install "godlp"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mcreekmore/godlp/releases/download/v0.1.1/godlp_0.1.1_linux_amd64.tar.gz"
      sha256 "ce11edc60b951e083a002b69f39ea78e998da550cc0825614a2b55c3fd811f19"

      def install
        bin.install "godlp"
      end
    end
  end
end
